-- Product review table for shop products
create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  user_id uuid not null,
  user_full_name text not null,
  user_avatar text,
  rating integer not null check (rating between 1 and 5),
  review_text text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  verified_purchase boolean not null default false
);

-- Helpful index for product feed/listing and ordering
create index if not exists product_reviews_product_id_created_at_idx
  on public.product_reviews (product_id, created_at desc);

create index if not exists product_reviews_user_id_idx
  on public.product_reviews (user_id);

-- Enable row level security
alter table public.product_reviews enable row level security;

-- Anyone can read product reviews
create policy if not exists "product_reviews_select_public"
  on public.product_reviews
  for select
  using (true);

-- Authenticated users can insert their own reviews
create policy if not exists "product_reviews_insert_authenticated"
  on public.product_reviews
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Users can update only their own reviews
create policy if not exists "product_reviews_update_owner"
  on public.product_reviews
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Users can delete only their own reviews
create policy if not exists "product_reviews_delete_owner"
  on public.product_reviews
  for delete
  to authenticated
  using (auth.uid() = user_id);
